services:
  # Note: This is for deployment, not development. For development, use docker-compose.dev.yml
  backend:
    container_name: backend
    image: ghcr.io/aaron-parker-cs/greenthumbtracker/greenthumb-backend:latest
    restart: always
    env_file:
      - .env
    environment:
      - NODE_ENV=development
    networks:
      default:
        aliases:
          - backend

  frontend:
    container_name: frontend
    image: ghcr.io/aaron-parker-cs/greenthumbtracker/greenthumb-frontend:latest
    restart:
      - always
    ports:
      - "80:80"
      - "443:443"
    env_file:
      - .env
    environment:
      - NODE_ENV=development
    volumes:
      - ./ssl/cert.pem:/etc/nginx/ssl/cert.pem
      - ./ssl/key.pem:/etc/nginx/ssl/key.pem                                                                  