services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: greenthumb-backend
    ports:
      - "8800:8800"
    volumes:
      - ./backend:/usr/src/app
    environment:
      - NODE_ENV=development
    
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: greenthumb-frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/usr/src/app
    environment:
      - NODE_ENV=development