name: Docker Build Check

on:
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # --- Build the backend image ---
      - name: Build backend image
        run: |
          docker build \
            -t backend:ci \
            ./backend

      # Optional: Run backend container tests
      #- name: Test backend container
      #  run: |
      #    docker run --rm my-backend:ci /bin/sh -c "echo 'Running backend tests...' && <your-backend-test-command>"

      # --- Build the frontend image ---
      - name: Build frontend image
        run: |
          docker build \
            -t frontend:ci \
            ./frontend

      # Optional: Run frontend container tests
      #- name: Test frontend container
      #  run: |
      #    docker run --rm my-frontend:ci /bin/sh -c "echo 'Running frontend tests...' && <your-frontend-test-command>"
